### PR TITLE
Add more cameras with batteries

### LINKED ISSUE #454: [Bug] Missing battery levels
**Describe the bug**
I have a Wyze Cam Outdoor V2 and a Wyze Video Doorbell Pro and neither of them report their battery status in Home Assistant.

image

In looking over the logs, I see that both report their "electricity" which seems to be their battery level.

**Expected behavior**
I would expect the two devices to report their battery levels (so I can be alerted by HA when they're running low)

**System configuration**
System: Docker
HA Version:  2023.1.7
WyzeApi Version: 0.1.17

**home-assistant.log**

[home-assistant_2023-01-27T18-23-15.793Z-onlywyze.log](https://github.com/JoshuaMulliken/ha-wyzeapi/files/10522067/home-assistant_2023-01-27T18-23-15.793Z-onlywyze.log)

### PR DESCRIPTION
**Pull request by magikid**
I discovered that two of my models can show their battery levels.  This enables that functionality for them.

Fixes #454

### CODE REVIEW

**Comment by magikid** [comment]
I've confirmed this resolves the issue locally by modifying the library, restarting home assistant, and checking the entities show up with batteries now:

image

**Comment by JoeSchubert** [comment]
LGTM. However, from what I've seen... Even on wired power, the doorbell reports a battery percentage. So, this will show that battery percentage even with a wired doorbell. I am unsure exactly what indicates that it is on wired power unless it is the blank string for 
"battery_charging_status": "",

as that is how mine appears being wired. 

I think it's worth including either way. However, I expect that we will get issues of "my wired doorbell is reporting battery percentages"

**Comment by magikid** [comment]
I don’t have the ability to hardwire mine. Could it be keeping the batteries topped off?

Could you give me an example of the json response for your hardwired one so I can compare them? I wouldn’t mind reworking this a little to only add the doorbell if it’s actually using batteries.

**Comment by JoeSchubert** [comment]
> Could you give me an example of the json response for your hardwired one so I can compare them?

This is the response from mine I pulled a couple weeks back. I don't know that it "keeps the batteries topped off" per se. The app doesn't report battery levels if it's on wired power. Like I said, I'm willing to bet that it's the value in one of these two keys that is different than yours, being on battery vs wired.

device_params > battery_charging_status
device_params > power_switch


{
    "binding_ts": 1667599768000,
    "binding_user_nickname": "email@email.com", //Modified to protect privacy, but this is the email address of the user who added the device
    "conn_state": 1,
    "conn_state_ts": 1671346891000,
    "device_params": {
        "accessory_switch": 0,
        "ai_notification_v2": 0,
        "audio_alarm_switch": 1,
        "battery_charging_status": "",
        "camera_thumbnails": {
            "thumbnails_ts": 1671590089648,
            "thumbnails_url": "url-to-thumbnails" //Modified to protect privacy, but this is url to thumbnails
        },
        "co_alarm_switch": 1,
        "comfort_standard_level": 2,
        "device_setting_channel": 0,
        "dongle_product_model": "",
        "dongle_switch": 0,
        "dtls": 0,
        "electricity": "84",
        "humidity": "0",
        "ip": "",
        "is_link_toy_car": 0,
        "is_temperature_humidity": "0",
        "main_device_dtls": 0,
        "motion_alarm_switch": 1,
        "p2p_id": "GW_BE1_MAC", //Modified to protect privacy, but this is the model combined with the MAC address
        "p2p_type": 0,
        "power_saving_mode_switch": 0,
        "power_switch": 1,
        "public_ip": "",
        "records_event_switch": 1,
        "smoke_alarm_switch": 1,
        "ssid": "",
        "temp_humi_room_type": 1,
        "temperature": "0"
    },
    "enr": "",
    "event_master_switch": 1,
    "firmware_ver": "0x2a26",
    "first_activation_ts": 1667599768000,
    "first_binding_ts": 1667599768000,
    "hardware_ver": "0.0.0.0",
    "is_in_auto": 0,
    "mac": "GW_BE1_MAC", //Modified to protect privacy, but this is the model combined with the MAC address
    "nickname": "Front door",
    "parent_device_enr": "",
    "parent_device_mac": "",
    "product_model": "GW_BE1",
    "product_model_logo_url": "",
    "product_type": "Camera",
    "push_switch": 1,
    "timezone_gmt_offset": -5.0,
    "timezone_name": "America/New_York",
    "user_role": 1
},

**Comment by JoeSchubert** [comment]
@magikid were you able to determine the field that indicates that your doorbell is on battery?

**Comment by magikid** [comment]
No luck.  That battery charging status field doesn't look like a good indication either because my battery doorbell is showing an empty field for it.

**Comment by JoeSchubert** [comment]
> No luck. That battery charging status field doesn't look like a good indication either because my battery doorbell is showing an empty field for it.

What's your response look like? With the couple sensitive fields edited out like in mine.

**Comment by JoshuaMulliken** [comment]
It seems like this feature is still in progress. @magikid can you work with @JoeSchubert to get this feature ready for addition?

**Pull request closed without merging**
